# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SmartLineLabeler
                                 A QGIS plugin
 create dynamic stacked labels for linestring layers
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-08-26
        copyright            : (C) 2020-2025 by Christoph Candido
        email                : christoph.candido@gmx.at
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SmartLineLabeler class from file SmartLineLabeler.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .SmartLineLabeler import SmartLineLabeler

    return SmartLineLabeler(iface)
